apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
      - image: localhost/dealership:latest
        imagePullPolicy: Never
        name: dealership
        ports:
        - containerPort: 8000
          hostPort: 8080
          protocol: TCP
      restartPolicy: Always

